[package]
name = "exact-maid"
version = "0.5.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/exact-rs/maid"
description = "🔨 An easy to use make alternative."

[dependencies]

log = "0.4.17"
home = "0.5.4"
toml = "0.5.11"
inquire = "0.5.3"
colored = "2.0.0"
serde = "1.0.152"
termcolor = "1.2.0"
just_macros = "0.2.0"
env_logger = "0.10.0"
serde_derive = "1.0.152"
text_placeholder = "0.4.0"
strip-ansi-escapes = "0.1.1"
clap-verbosity-flag = "2.0.0"
clap = { version = "4.1.1", features = ["derive"] }
serde_json = "1.0.96"
optional-field = "0.1.3"
