# import tasks and enviroment from other files
import = ["scripts/build.toml", "scripts/test.toml"]

[project]
name = "maid"
version = "0.8.0"

# build on a remote server
[project.server]
address = { host = "localhost", port = 3500, ssl = false }
token = "test_token"

# global enviroment
[env]
BOOL = false
STRING = 'test'
TYPE = '%{dir.home} %{env.STRING} %{arg.1}'
ARR = ['hello', 'world']
VERSION='0.7.0'

[tasks.build]
info = "Build binaries"
depends = ["clean"]
script = [
   # "maid clean -q",
   "cargo build --release", 
   "mv target/release/maid bin/maid",
   "mv target/release/maid_server bin/maid_server",
   "mv target/release/exit_test bin/exit_test"
]

[tasks.build.cache]
path = "crates"
target = [
   "bin/maid", 
   "bin/exit_test", 
   "bin/maid_server"
]

[tasks.build.remote]
image = "rust"
push = ["crates", "Cargo.toml", "Cargo.lock"]
pull = [
   "bin/maid", 
   "bin/exit_test", 
   "bin/maid_server"
]

# basic task definition 
[tasks]
clean = { info = "Clean binary files", script = ["rm -rf bin", "mkdir bin"] }
install = { info = "Move binary file", script = ["sudo cp bin/maid /usr/local/bin", "echo Copied binary!"], depends = ["build"] }
buildall = { info = "build all", script = ["rm -rf build", "mkdir build", "maid _build_macos", "maid _build_linux", "maid _build_windows"] }