[tasks]
# test dependencies
test = { script = "echo hello world", depends = ["dep1", "dep2", "exit bad"] }
dep1 = { script = "sleep 3", hide = true }
dep2 = { script = "sleep 2", hide = true }

# other tests
hidden = { script = "echo hidden", hide = true }
debug = { info = "debug env", path="src", script = ["echo %{env.BOOL}", "echo %{env.STRING}", "echo %{arg.1}", "echo %{dir.current}", "echo %{dir.home}", "echo %{env.TYPE}", "echo %{env.ARR}", "echo %{os.platform}", "echo %{os.arch}"] }
broken = { info = "bad task", script = ["this_does_not_exist"] }

# exit types
exit = { script = "maid 'exit %{arg.1}'" }
"exit bad" = { script = ["exit_test 0", "exit_test 1", "exit_test 2"], hide = true }
"exit good" = { script = ["exit_test 2", "exit_test 1", "exit_test 0"], hide = true }
